accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
]

employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index")
]

trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    path('customers/', include('customers.urls')),
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    """Our custom user model that adds a new field to the default django user model"""
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.username

customers/models.py
from django.db import models


class Customer(models.Model):
    PICKUP_DAYS = (
        ('Mo', 'Monday'),
        ('Tu', 'Tuesday'),
        ('We', 'Wednesday'),
        ('Th', 'Thursday'),
        ('Fr', 'Friday'),
    )
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=None, on_delete=models.CASCADE)
    address = models.ForeignKey('customers.Address', default=None, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey('customers.Account', default=None, null=True, on_delete=models.CASCADE)
    weekly_pickup = models.CharField(max_length=2, choices=PICKUP_DAYS, null=True, default='Mo')
    extra_pickup = models.DateField(null=True)
    suspension_start = models.DateField(null=True)
    suspension_end = models.DateField(null=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    building_number = models.IntegerField()
    street_name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField()


class Account(models.Model):
    account_number = models.IntegerField()
    account_balance = models.DecimalField(max_digits=10, decimal_places=2)
    last_charge = models.DateField(null=True)

employees/models.py
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)
    zipcode = models.IntegerField()

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(UserCreationForm):
    """This form allows our custom user model to be registered with an added field reflecting its employee status"""
    is_employee = forms.BooleanField(label="Check to register as employee", required=False)

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "is_employee")

    def save(self, commit=True):
        # Overriding the save method to add user to auth group of Employee or Customer depending on if box is checked
        user = super(CustomUserForm, self).save(commit=False)
        user.is_employee = self.cleaned_data["is_employee"]

        if commit:
            user.save()
            if user.is_employee:
                employees = Group.objects.get(name="Employees")
                employees.user_set.add(user)
            else:
                customers = Group.objects.get(name="Customers")
                customers.user_set.add(user)
        return user



accounts/views.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import CustomUserForm


class RegisterView(generic.CreateView):
    """Allows user to register with the custom form we created"""
    form_class = CustomUserForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from . import helpers
from .models import Customer

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # query for customer object
    # IF customer does not exist, call create function
    # ELSE, pass customer object as context to render function
    # get the logged in user within any view function
    user = request.user
    customer = Customer.objects.filter(user=user)
    if not customer:
        return render(request, 'customers/create.html')
    else:
        context = {
            'customer': customer
        }
        return render(request, 'customers/index.html', context)


def create(request):
    # assign user as customer user foreign key
    # add customer name to customer object
    # use helper function to add address to new address object
    # use helper function to generate address and add as foreign key
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        customer = Customer()
        customer.user = user
        customer.name = name
        customer.save()
        helpers.create_address(customer, request)
        helpers.create_account(customer)
        return render(request, 'customers/index.html', context={
            'customer': customer
        })
    else:
        return render(request, 'customers/create.html')

employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def index(request):
    # Get the Customer model from the other app, it can now be used to query the db
    Customer = apps.get_model('customers.Customer')
    return render(request, 'employees/index.html')

trash_collector/views.py
from django.shortcuts import redirect, render


def group_redirect(request):
    """This single view function redirects a user to the customer or employee index if they are in either group"""
    if request.user.groups.filter(name="Customers").exists():
        return redirect('/customers/')
    elif request.user.groups.filter(name="Employees").exists():
        return redirect('/employees/')
    else:
        # If user is in neither group, get sent back to home
        print(request.user)
        return render(request, 'home.html')

customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %}{% block header %} Create Customer {% endblock %}{% endblock %}

{% block content %}
<form method="post" action="{% url 'customers:create' %}">
    {% csrf_token%}
    <div class="form-group">
        <label for="name">Name</label><br>
        <input type="text" class="form-control" name="name" id="name"><br>
    </div><br>
    <p>Address Information</p>
    <div class="form-group">
        <label for="building_number">Building Number</label><br>
        <input type="text" class="form-control" name="building_number" id="building_number"><br>
    </div>
    <div class="form-group">
        <label for="street_name">Street Name</label>
        <input type="text" class="form-control" name="street_name" id="street_name">
    </div>
    <div class="form-group">
        <label for="city">City</label>
        <input type="text" class="form-control" name="city" id="city">
    </div>
    <div class="form-group">
        <label for="state">State</label><br>
        <input type="text" class="form-control" name="state" id="state">
    </div>
    <div class="form-group">
        <label for="zipcode">Zip Code</label><br>
        <input type="text" class="form-control" name="zipcode" id="zipcode">
    </div>
    <div class="form-group">
        <input type="submit" value="Add Customer!" class="btn btn-outline-primary">
    </div>
</form>
{% endblock %}

customers/templates/customers/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Customer Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <p>Customer Navbar</p>
    {% elif group.name == "Employees" %}
    <p>Employee Navbar</p>
    {% endif %}
  {% endfor %}
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
{# This is the parent view that can be inherited by any other views #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Portal{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}